-- Property Owner Portal + Tax Declaration Request workflow.
-- Run this in Supabase SQL Editor.

alter table public.tax_declarations
  add column if not exists submitted_by uuid references auth.users(id),
  add column if not exists submitted_by_email text,
  add column if not exists submitted_at timestamptz default now();

create index if not exists tax_declarations_submitted_by_idx
  on public.tax_declarations(submitted_by);

-- ---------------------------------------------------------
-- PROPERTY OWNER ACCOUNTS
-- ---------------------------------------------------------
create table if not exists public.property_owner_accounts (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text not null default '',
  contact_number text default '',
  address text default '',
  account_status text not null default 'Pending'
    check (account_status in ('Pending','Verified','Locked')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists property_owner_accounts_status_idx
  on public.property_owner_accounts(account_status);

alter table public.property_owner_accounts enable row level security;

drop policy if exists "Property owners can create own account profile" on public.property_owner_accounts;
create policy "Property owners can create own account profile"
on public.property_owner_accounts for insert to anon, authenticated
with check (id = auth.uid());

drop policy if exists "Property owners can view own account profile" on public.property_owner_accounts;
create policy "Property owners can view own account profile"
on public.property_owner_accounts for select to authenticated
using (id = auth.uid());

-- The project currently uses a custom Assessor login rather than Supabase Auth.
-- These policies allow the existing Assessor dashboard to manage the portal tables.
-- If your production deployment has a server-side admin API, replace these with
-- server/RPC policies tied to that admin identity.
drop policy if exists "Portal admin can view property owner accounts" on public.property_owner_accounts;
create policy "Portal admin can view property owner accounts"
on public.property_owner_accounts for select to anon, authenticated
using (true);

drop policy if exists "Portal admin can update property owner accounts" on public.property_owner_accounts;
create policy "Portal admin can update property owner accounts"
on public.property_owner_accounts for update to anon, authenticated
using (true) with check (true);

drop policy if exists "Portal admin can delete property owner accounts" on public.property_owner_accounts;
create policy "Portal admin can delete property owner accounts"
on public.property_owner_accounts for delete to anon, authenticated
using (true);

-- ---------------------------------------------------------
-- INDIVIDUAL NOTICES
-- ---------------------------------------------------------
create table if not exists public.property_owner_notices (
  id bigint generated by default as identity primary key,
  property_owner_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Notice from Assessor''s Office',
  message text not null default '',
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists property_owner_notices_owner_idx
  on public.property_owner_notices(property_owner_id, created_at desc);

alter table public.property_owner_notices enable row level security;

drop policy if exists "Property owners can view own notices" on public.property_owner_notices;
create policy "Property owners can view own notices"
on public.property_owner_notices for select to authenticated
using (property_owner_id = auth.uid());

drop policy if exists "Portal admin can manage notices" on public.property_owner_notices;
create policy "Portal admin can manage notices"
on public.property_owner_notices for all to anon, authenticated
using (true) with check (true);

-- ---------------------------------------------------------
-- TAX DECLARATION REQUESTS
-- ---------------------------------------------------------
create table if not exists public.tax_declaration_requests (
  id bigint generated by default as identity primary key,
  submitted_by uuid not null references auth.users(id) on delete cascade,
  submitted_by_email text default '',
  tax_declaration_id text,
  td_no text not null,
  property_identification_no text not null,
  purpose text not null,
  valid_government_id_url text not null,
  proof_of_ownership_url text not null,
  supporting_document_image_url text not null,
  authorization_letter_url text,
  verification_status text not null default 'Pending'
    check (verification_status in ('Pending','Rejected','Released')),
  admin_notes text default '',
  created_at timestamptz not null default now(),
  released_at timestamptz
);

create index if not exists tax_declaration_requests_owner_idx
  on public.tax_declaration_requests(submitted_by, created_at desc);

create index if not exists tax_declaration_requests_status_idx
  on public.tax_declaration_requests(verification_status);

alter table public.tax_declaration_requests enable row level security;

drop policy if exists "Property owners can create own requests" on public.tax_declaration_requests;
create policy "Property owners can create own requests"
on public.tax_declaration_requests for insert to authenticated
with check (submitted_by = auth.uid());

drop policy if exists "Property owners can view own requests" on public.tax_declaration_requests;
create policy "Property owners can view own requests"
on public.tax_declaration_requests for select to authenticated
using (submitted_by = auth.uid());

drop policy if exists "Portal admin can view requests" on public.tax_declaration_requests;
create policy "Portal admin can view requests"
on public.tax_declaration_requests for select to anon, authenticated
using (true);

drop policy if exists "Portal admin can update requests" on public.tax_declaration_requests;
create policy "Portal admin can update requests"
on public.tax_declaration_requests for update to anon, authenticated
using (true) with check (true);

-- ---------------------------------------------------------
-- STORAGE
-- ---------------------------------------------------------
-- The existing tax-declarations bucket is reused.
-- These policies permit authenticated Property Owners to upload
-- their request documents and let the existing dashboard read them.
drop policy if exists "Property owners upload portal documents" on storage.objects;
create policy "Property owners upload portal documents"
on storage.objects for insert to authenticated
with check (bucket_id = 'tax-declarations');

drop policy if exists "Portal users read tax declaration documents" on storage.objects;
create policy "Portal users read tax declaration documents"
on storage.objects for select to anon, authenticated
using (bucket_id = 'tax-declarations');
